name: renew

on:
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            await exec.exec('npx', ['mkcert', 'create-ca']);
            await exec.exec('npx', ['mkcert', 'create-cert']);
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            cert.crt
            cert.key
          commit-msg: "fix: renew certificates"
          github-token: ${{ secrets.GITHUB_TOKEN }}
